### ISSUE TITLE
Support non-RPM artifacts

### ISSUE THREAD

**Issue by lmacken** [fedora-infra/bodhi#653]
In the future we'd like bodhi to support more than just RPM artifacts, such as OSTrees, containers, xdg-apps, etc.

- [x] Document the existing REST API - #1323
- [x] Database model changes - #1324
- [x] REST API changes - #1325
- [x] Modify fedmsgs so they identify which content type is referenced - #1326
- [x] Python bindings changes - #1327
- [x] CLI modifications - #1328
- [x] Documentation
- [x] Web UI changes - #1329
- [ ] Masher modifications to the push process - #1330
- [x] Unit tests

**Comment by AdamWill** [comment]
It would be good to know ahead of time how we'll be able to tell the different types of update apart in:

i) API query results
ii) fedmsgs

**Comment by bowlofeggs** [comment]
Thanks @AdamWill, I added those to the list above. I am planning to break the above list into separate tickets, and we can just use this one as an overview.

I'm debating whether to try to maintain backwards compatibility or just make everything always require the type to be specified (and name the version Bodhi 3 to reflect the breaking change). Explicit is better than implicit ☺

**Comment by ralphbean** [comment]
Almost there.  :p
